### ISSUE TITLE
"Incorrect Column Name" issue

### ISSUE THREAD

**Issue by malspaugh** [abtassociates/DQ_CE#79]
These warnings are incorrect. Per the CSV spec, the p in "Workplace" is not capitalized.

Incorrect Column Name | Warning | The WorkplaceViolenceThreats column in the   Exit file should be spelled like WorkPlaceViolenceThreats
-- | -- | --
Incorrect Column Name | Warning | The WorkplacePromiseDifference column in the Exit file should be spelled   like WorkPlacePromiseDifference

**Comment by kiadso** [comment]
fix forthcoming- thank you @malspaugh!
